export const KEYS = {
  login: 'login',
  getMe: 'getMe',
  getAllListOrganization: "getAllListOrganization",
  getAllListDepartment: "getAllListDepartment",
  getListOrganizationSelf: "getListOrganizationSelf",
  getListUsersManagment: "getListUsersManagment",
  getUserRoles: "getUserRoles",
  getEmployeeList: "getEmployeeList",
  getVisitorList: "getVisitorList",
  getPolicyList: "getPolicyList",
  getUsersMe: "getUsersMe",
  getPolicyResources: "getPolicyResources",
  getPolicyGroups: "getPolicyGroups",
  getEmployeeGroups: "getEmployeeGroups",
  employeeBulk: "employeeBulk",
  getDoorGates: "getDoorGates",
  getDoorForDevices: "getDoorForDevices",
  getCredentialByEmployee: "getCredentialByEmployee",
  credentials: "credentials",
  getGatesByIdDevices: "getGatesByIdDevices",
  uploadPhotoByEmployee: "uploadPhotoByEmployee",
  devicesEmployeeAssign: "devicesEmployeeAssign",
  hikvisionEmployeeSync: "hikvisionEmployeeSync",
  attendacesForEmployee: "attendacesForEmployee",
  employeeSchedulePlan: "employeeSchedulePlan",
  employeePlansAssign: "employeePlansAssign",
  attendancesReason: "attendancesReason",
  employeeJobPosition: "employeeJobPosition",
  deviceForDoor: "deviceForDoor",
  employeeTimesheet: "employeeTimesheet",
  actionAttendancesList:"actionAttendancesList",
  employeeByAttendancesCard:"employeeByAttendancesCard"
};
