export const URLS = {
  login: '/api/users-permissions/login',
  getMe: '/api/employees/me',
  getAllListOrganization: "/api/organizations",
  getAllListDepartment: "/api/departments",
  getAllListDepartmentSelf: "/api/departments/self",
  getListOrganizationSelf: "/api/organizations/self",
  getListUsersManagment: "/api/users",
  getUserRoles: "/api/users/roles",
  getEmployeeList: "/api/employees",
  getVisitorList: "/api/visitors",
  getPolicyList: "/api/policies",
  getUsersMe: "/api/users/me",
  getPolicyResources: "/api/policies/resources",
  getPolicyGroups: "/api/policies/groups",
  getEmployeeGroups: "/api/employee/groups",
  getOnetimeCodes: "/api/onetime-codes",
  employeeBulk: "/api/employees/bulk",
  getDoorGates: "/api/gates",
  getDoorForDevices: "/api/devices",
  getCredentialByEmployee: "/api/credentials/by-employee",
  credentials: "/api/credentials",
  getGatesByIdDevices: "/api/gates",
  uploadPhotoByEmployee: "/api/employees/upload-photo",
  devicesEmployeeAssign: "/api/devices/assign-employees",
  hikvisionEmployeeSync: "/api/employee-sync",
  attendacesForEmployee: "/api/attendances",
  employeeSchedulePlan: "/api/employee-plans",
  employeePlansAssign: "/api/employee-plans/assign",
  attendancesReason: "/api/reasons",
  employeeJobPosition: "/api/jobs",
  deviceForDoor: "/api/devices/openDoor",
  employeeTimesheet: "/api/reports/attendance",
  actionAttendancesList: "/api/action",
  employeeByAttendancesCard: "/api/reports/attendance/statics",
  dashbord: "/api/dashboard",
  dashboardLineChart: "/api/dashboard/chart",
  doorDevice: "/api/devices/connectDevicesToGate",
  devicesGateEmployee: "/api/devices/gate",
  deviceGateSyncEmployee: "/api/devices/gate/sync-credentials",
  visitorByAttendancesCard: "/api/reports/attendance/statics",
  removeAssignEmployee: "/api/devices/remove-employees",
  activeOneTimeCode: "/api/onetime-codes",
  getDeviceSettingsInfo: "/api/devices/get-capabilities",
  deviceDisplay: "/api/devices/display",
  deviceCredentialType: "/api/devices/credential-auth",
  dashboardToday: "/api/dashboard/today",
  employeeCredentialFileUpload: "/api/credentials/upload-photo",
  oneTimeCodeExpire: "/api/onetime-codes/validate",
  dashboardTodayTop: "/api/dashboard/top-employees",
  dashboardTodayBottom: '/api/dashboard/top-employees',
  actionAllList: "/api/action/all-actions",
  absences: "/api/absences",
  employeePlanHistoryChangeSchedules: "/api/employee-plans/history-change-schedules",
  employeeAbsences: "/api/employee-absences",
  employeeAssignDevice: "/api/devices/device-employees",
  birthdayEmployee: "/api/dashboard/birthdays",
  getComputerList: "/api/computers",
  getScreenShot: "/api/monitoring/screenshots",
  getUserSession: "/api/monitoring/user-sessions",
  getKeyLogs: "/api/monitoring/keylogs",
  getVisitedSites: "/api/monitoring/visited-sites",
  getActiveWindows: "/api/monitoring/active-windows",
  getPolicyEnum:"/api/policies/enum",
  getComputerUserList: "/api/computer-users",
  getUsefulApps:"/api/monitoring/statistics/useful-apps",
  getUnproductiveApps:"/api/monitoring/statistics/unproductive-apps",
  getUsefulSites:"/api/monitoring/statistics/useful-sites",
  getUnproductiveSites:"/api/monitoring/statistics/unproductive-sites",
  getUsageDetails:"/api/monitoring/statistics/usage-details",
  dashboardEmployeeProductivityRanking: "/api/dashboard/employee-productivity-ranking",
  dashboardOverallEmployeeRanking: "/api/dashboard/overall-employee-ranking",
  
};
